export { Kage, FONTTYPE, KShotai } from "./lib/kage.js";
export { Polygons } from "./lib/polygons.js";
export { Polygon } from "./lib/polygon.js";
//export const kage_export = {Kage: Kage, FONTTYPE: FONTTYPE, Polygons: Polygons};
// Object.defineProperty(exports, "__esModule", { value: true });
// var kage_1 = require("./lib/kage");
// Object.defineProperty(exports, "Kage", { enumerable: true, get: function () { return kage_1.Kage; } });
// var polygons_1 = require("./lib/polygons");
// Object.defineProperty(exports, "Polygons", { enumerable: true, get: function () { return polygons_1.Polygons; } });
// var buhin_1 = require("./lib/buhin");
// Object.defineProperty(exports, "Buhin", { enumerable: true, get: function () { return buhin_1.Buhin; } });
// var kage_2 = require("./lib/kage");
// exports.default = kage_2.Kage;
